# Generated by Django 4.1.2 on 2022-12-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='films.category', verbose_name='Category'),
        ),
    ]
