# Generated by Django 4.1.2 on 2022-12-20 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_films_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='date_made',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
